baseurl: https://blog.steven53.top
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: Steven's Blog
copyright: Steven Wu

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /favicon.ico # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

    footer:
        since: 2023
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🍥
        subtitle: 
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: true
        toc: true
        readingTime: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
#        provider: disqus
        provider: giscus

        giscus:
            repo: "steven52880/blog"
            repoID: "R_kgDOKLDlpw"
            category: "Announcements"
            categoryID: "DIC_kwDOKLDlp84CZFeg"
            mapping: "title"
            strict: 0
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition: "bottom"
            lang: "zh-CN"

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: false
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true
    
    customcss:
        - "css/custom.css"
    customjs:
    icpLicense: "粤ICP备20028373号-1"

disqusShortname: "steven53-blog"

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social: []
#        - identifier: github
#          name: GitHub
#          url: https://github.com/steven52880
#          params:
#              icon: brand-github

#        - identifier: twitter
#          name: Twitter
#          url: https://twitter.com/steven52880
#          params:
#              icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        ordered: true
        startLevel: 2
        endLevel: 4
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNos: true
        lineNoStart: 1
        lineNumbersInTable: true
        tabWidth: 4
